# fly.toml app configuration file generated for flask-mongodb-fly-wild-sky-7177 on 2024-11-03T09:49:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flask-mongodb-fly-wild-sky-7177'
primary_region = 'sea'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[processes]
  app = 'gunicorn app:app'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
